import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { join, extname } from 'node:path';
import puppeteer from 'puppeteer-core';
const dist='/home/dicelabs/sitexr/dist';
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.bin':'application/octet-stream','.glb':'model/gltf-binary'};
const server=createServer(async(req,res)=>{try{let p=decodeURIComponent(new URL(req.url,'http://x').pathname);if(p.endsWith('/'))p+='index.html';const f=join(dist,p);await stat(f);res.writeHead(200,{'content-type':MIME[extname(f)]??'application/octet-stream'});res.end(await readFile(f));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${server.address().port}/`;
const S='/tmp/claude-1000/-home-dicelabs/c5d5457e-a023-40c3-ab5b-7b33af72d887/scratchpad';
const b=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:'new',args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const p=await b.newPage();await p.setViewport({width:1280,height:820});
const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.evaluateOnNewDocument(()=>{try{localStorage.setItem('sitexr.comfort.v1',JSON.stringify({tutorialDone:true,quality:'high'}));}catch{}});
await p.goto(`${base}?site=office`,{waitUntil:'domcontentloaded'});
await p.waitForFunction(()=>!document.getElementById('enter')?.disabled,{timeout:600000});
await p.evaluate(()=>document.getElementById('enter').click());
await new Promise(r=>setTimeout(r,4000));
// desktop: press Change site
await p.evaluate(()=>document.getElementById('hud-site').click());
await new Promise(r=>setTimeout(r,1200));
await p.screenshot({path:`${S}/switch-desktop.png`});
const listed=await p.evaluate(()=>[...document.querySelectorAll('#sites .site')].map(e=>e.dataset.id));
console.log('desktop lists:', listed.join(', '));
console.log('errors:', errs.length?errs.slice(0,3).join(' | '):'none');
await b.close();server.close();
